config/routes.rb
Ponzi::Application.routes.draw do
  resources :old_games

  resources :games do
    get 'play', on: :member
  end

  resources :users do
    resources :accounts
  end

end

app/models/old_game.rb
class OldGame < ActiveRecord::Base
	has_one :game
end

app/controllers/old_games_controller.rb
class OldGamesController < ApplicationController
  # GET /old_games
  # GET /old_games.json
  def index
    @old_games = OldGame.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @old_games }
    end
  end

  # GET /old_games/1
  # GET /old_games/1.json
  def show
    @old_game = OldGame.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @old_game }
    end
  end

  # GET /old_games/new
  # GET /old_games/new.json
  def new
    @old_game = OldGame.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @old_game }
    end
  end

  # GET /old_games/1/edit
  def edit
    @old_game = OldGame.find(params[:id])
  end

  # POST /old_games
  # POST /old_games.json
  def create
    @old_game = OldGame.new(params[:old_game])

    respond_to do |format|
      if @old_game.save
        format.html { redirect_to @old_game, notice: 'Old game was successfully created.' }
        format.json { render json: @old_game, status: :created, location: @old_game }
      else
        format.html { render action: "new" }
        format.json { render json: @old_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /old_games/1
  # PUT /old_games/1.json
  def update
    @old_game = OldGame.find(params[:id])

    respond_to do |format|
      if @old_game.update_attributes(params[:old_game])
        format.html { redirect_to @old_game, notice: 'Old game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @old_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /old_games/1
  # DELETE /old_games/1.json
  def destroy
    @old_game = OldGame.find(params[:id])
    @old_game.destroy

    respond_to do |format|
      format.html { redirect_to old_games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/old_games_helper.rb
module OldGamesHelper
end

app/views/old_games/_form.html.erb
<%= form_for(@old_game) do |f| %>
  <% if @old_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@old_game.errors.count, "error") %> prohibited this old_game from being saved:</h2>

      <ul>
      <% @old_game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/old_games/edit.html.erb
<h1>Editing old_game</h1>

<%= render 'form' %>

<%= link_to 'Show', @old_game %> |
<%= link_to 'Back', old_games_path %>

app/views/old_games/index.html.erb
<h1>Listing old_games</h1>

<table>
  <tr>
    <th>Game</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @old_games.each do |old_game| %>
  <tr>
    <td><%= old_game.game_id %></td>
    <td><%= link_to 'Show', old_game %></td>
    <td><%= link_to 'Edit', edit_old_game_path(old_game) %></td>
    <td><%= link_to 'Destroy', old_game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Old game', new_old_game_path %>

app/views/old_games/new.html.erb
<h1>New old_game</h1>

<%= render 'form' %>

<%= link_to 'Back', old_games_path %>

app/views/old_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @old_game.game_id %>
</p>


<%= link_to 'Edit', edit_old_game_path(@old_game) %> |
<%= link_to 'Back', old_games_path %>