config/routes.rb
Ponzi::Application.routes.draw do
  resources :old_games

  resources :games do
    get 'play', on: :member
  end

  resources :users do
    resources :accounts
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user

	validates :amount, presence: true,
				numericality: { greater_than_or_equal_to: 0.0 }

	BITCOIN_ADDRESS_REGEX = /^(1|3)[1-9A-HJ-NP-Za-km-z]{27,34}/
	validates :daddr, presence: true,
					  format: { with: BITCOIN_ADDRESS_REGEX }
	validates :waddr, presence: true,
					  format: { with: BITCOIN_ADDRESS_REGEX }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to user_account_url(user_id: @account.user_id, account: @account.id), notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account, url: user_accounts_path(@user)) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :daddr %><br />
    <%= f.text_field :daddr %>
  </div>
  <div class="field">
    <%= f.label :waddr %><br />
    <%= f.text_field :waddr %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Daddr</th>
    <th>Waddr</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.amount %></td>
    <td><%= account.daddr %></td>
    <td><%= account.waddr %></td>
    <td><%= account.user_id %></td>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_user_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', user_accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @account.amount %>
</p>

<p>
  <b>Daddr:</b>
  <%= @account.daddr %>
</p>

<p>
  <b>Waddr:</b>
  <%= @account.waddr %>
</p>

<p>
  <b>User:</b>
  <%= @account.user_id %>
</p>


<%= link_to 'Edit', edit_user_account_path(@account) %> |
<%= link_to 'Back', user_accounts_path %>